services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - 3306:3306
    volumes:
      - app-db:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    image: redis
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
volumes:
  app-db:
