info:
  contact: {}
paths:
  /ping:
    get:
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - Health
swagger: "2.0"
